language: java
jdk: oraclejdk8

include:
    - stage: trigger downstream
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
          sh trigger-travis.sh WeatherAdminJEE https://github.com/WeatherAdminJEE/CommonModel $TRAVIS_ACCESS_TOKEN
        fi

script:
  - mvn install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=cedricg44-github -Dsonar.login=420e76b14840bcdbde5f211269db337969576cbf -Dsonar.branch=master
